### ISSUE TITLE
Tensor pushing from GPU to CPU

### ISSUE THREAD

**Issue by Salvatore-tech** [SpadeLiu/Lac-GwcNet#8]
Good evening, 
I'm bit struggling with the storing place of tensors, in fact when running `python KITTI_ft.py --data_path /home/s.starace/Dataset/KITTI_2015/training \
				   --load_path ./preTrained/SceneFlow.pth`  
It suppose that tensors should be pushed first on the CPU before converting them through numpy... could you confirm that?
Thanks in advance 
[tensorErrorLog.txt](https://github.com/SpadeLiu/Lac-GwcNet/files/9176389/tensorErrorLog.txt)

**Comment by SpadeLiu** [comment]
> 

Hi,

Yes, I think so. You can either **move "disp_true" onto CPU after model forward process** or **don't push it on GPU at first and create a zero matrix which has the same shape as "disp_true" and replace "disp_true" with it as the model input**. Now I am not convenient to change the code. After 11 hours, I will upload a new version.

**Comment by SpadeLiu** [comment]
> Good evening, I'm bit struggling with the storing place of tensors, in fact when running `python KITTI_ft.py --data_path /home/s.starace/Dataset/KITTI_2015/training \ --load_path ./preTrained/SceneFlow.pth` It suppose that tensors should be pushed first on the CPU before converting them through numpy... could you confirm that? Thanks in advance [tensorErrorLog.txt](https://github.com/SpadeLiu/Lac-GwcNet/files/9176389/tensorErrorLog.txt)

Hi，

Could you please try the lateset code?

**Comment by Salvatore-tech** [comment]
> > Good evening, I'm bit struggling with the storing place of tensors, in fact when running `python KITTI_ft.py --data_path /home/s.starace/Dataset/KITTI_2015/training \ --load_path ./preTrained/SceneFlow.pth` It suppose that tensors should be pushed first on the CPU before converting them through numpy... could you confirm that? Thanks in advance [tensorErrorLog.txt](https://github.com/SpadeLiu/Lac-GwcNet/files/9176389/tensorErrorLog.txt)
> 
> Hi，
> 
> Could you please try the lateset code?

Everything is alright after db029f8 
I'll close the issue, thanks again!
